//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSelector2.Model
{
    using System;
    
    public partial class FilmEF
    {
        public Nullable<long> lokata { get; set; }
        public int id { get; set; }
        public int srednia { get; set; }
        public string tytul { get; set; }
        public string tytul_org { get; set; }
        public string rezyseria { get; set; }
        public Nullable<int> udzial { get; set; }
        public int max { get; set; }
        public Nullable<decimal> imdb { get; set; }
        public string kategoria { get; set; }
        public Nullable<int> dlugosc { get; set; }
        public string obsada { get; set; }
        public string zrodlo { get; set; }
        public Nullable<bool> hit { get; set; }
        public Nullable<System.DateTime> obejrzany { get; set; }
        public string poster_link { get; set; }
        public string opis { get; set; }
        public string link { get; set; }
        public string kraj { get; set; }
        public Nullable<int> rok { get; set; }
        public Nullable<bool> nieaktywny { get; set; }
    }
}
