//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSelector2.Model
{
    using System;
    
    public partial class SkresleniaEF
    {
        public int id { get; set; }
        public string nick { get; set; }
        public Nullable<int> ilosc { get; set; }
        public Nullable<int> lokata { get; set; }
    }
}
