//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSelector2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tytuly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tytuly()
        {
            this.turnieje = new HashSet<turnieje>();
        }
    
        public int id { get; set; }
        public string tytul { get; set; }
        public string tytul_org { get; set; }
        public string rezyseria { get; set; }
        public Nullable<int> rok { get; set; }
        public string kategoria { get; set; }
        public Nullable<int> dlugosc { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> data_dodania { get; set; }
        public Nullable<System.DateTime> obejrzany { get; set; }
        public Nullable<int> ocena { get; set; }
        public string obsada { get; set; }
        public string opis { get; set; }
        public string kraj { get; set; }
        public Nullable<decimal> imdb { get; set; }
        public string zrodlo { get; set; }
        public Nullable<bool> hit { get; set; }
        public string poster_link { get; set; }
        public Nullable<bool> nieaktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turnieje> turnieje { get; set; }
        public virtual tytuly tytuly1 { get; set; }
        public virtual tytuly tytuly2 { get; set; }
    }
}
